name = "tech-trend-blog"
compatibility_date = "2024-10-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "tech-trend-blog"
database_id = "YOUR_DATABASE_ID"

[vars]
EARLIEST_DATE = "2025-12-25"
